version: "3.7"

services:
  order-service-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: order-service-zookeeper
    expose:
      - 2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  order-service-kafka:
    image: confluentinc/cp-kafka:latest
    container_name: order-service-kafka
    expose:
      - 9092
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=order-service-zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

  order-service-redis:
    image: redis:latest
    container_name: order-service-redis
    expose:
      - 6379
    ports:
      - 6379:6379

  order-service-mysql:
    image: mysql:5
    container_name: order-service-mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - "mysql:/var/lib/mysql"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

volumes:
  mysql: